ALTER SESSION SET CONTAINER=XEPDB1;

alter session set "_ORACLE_SCRIPT"=true;


/*  creacion del Tablespace */
CREATE TABLESPACE BASEDATOSTP
LOGGING
DATAFILE '/opt/oracle/oradata/XE/XEPDB1/basedatosp.dbf'
SIZE 45M REUSE
AUTOEXTEND ON 
NEXT 22500 K MAXSIZE 135M;

ALTER SESSION SET CONTAINER=XEPDB1;

alter session set "_ORACLE_SCRIPT"=true;


create user BASETP identified by BASETP
    DEFAULT TABLESPACE BASEDATOSTP
    TEMPORARY TABLESPACE TEMP;
GRANT DBA TO BASETP WITH ADMIN OPTION;

conn BASETP@XEPDB1


/**CREACION DE LAS TABLAS **/