ALTER SESSION SET CONTAINER=XEPDB1;

alter session set "_ORACLE_SCRIPT"=true;


/*  creacion del Tablespace */
CREATE TABLESPACE BASEDATOSTP
LOGGING
DATAFILE '/opt/oracle/oradata/XE/XEPDB1/basedatosp.dbf'
SIZE 45M REUSE
AUTOEXTEND ON 
NEXT 22500 K MAXSIZE 135M;

ALTER SESSION SET CONTAINER=XEPDB1;

alter session set "_ORACLE_SCRIPT"=true;


create user BASETP identified by BASETP
    DEFAULT TABLESPACE BASEDATOSTP
    TEMPORARY TABLESPACE TEMP;
GRANT DBA TO BASETP WITH ADMIN OPTION;

conn BASETP@XEPDB1


/**CREACION DE LAS TABLAS **/

/* CREACION DE TABLAS */
CREATE TABLE RESERVA(
 CODIGO NUMBER (12) GENERATED ALWAYS AS IDENTITY 
 START WITH 1 
MINVALUE 1
MAXVALUE 99999999
INCREMENT BY 1 NOCACHE NOCYCLE,
FECHA_RESERVA DATE NOT NULL,
HUESPED_TITULAR NUMBER (10) NOT NULL,
MONTO_TOTAL NUMBER(10)NOT NULL,
SALDO_ABONAR NUMBER(10)NOT NULL,
CHECK_IN DATE NOT NULL,
CHECK_OUT DATE NOT NULL,
NUM_HABITACION NUMBER (5) NOT NULL,
ESTADO VARCHAR2(1) NOT NULL,
CODIGO_CANAL NUMBER(5) NOT NULL
);

CREATE TABLE CARGO_RESERVA(
CODIGO_CARGO NUMBER(10) NOT NULL,
CODIGO_RESERVA NUMBER (12) NOT NULL,
ID_PROD_SERV NUMBER (5) NOT NULL,
PRECIO_UNITARIO NUMBER(10) NOT NULL,
CANTIDAD NUMBER (5) NOT NULL,
APLICAR_COBRO VARCHAR2(1) NOT NULL,
CODIGO_FACTURA NUMBER(5)
);

CREATE TABLE OCUPANTE (
CODIGO_OCUPANTE NUMBER(10) NOT NULL,
CODIGO_RESERVA NUMBER(12) NOT NULL,
FEC_HORA_ENTRADA DATE NOT NULL,
FEC_HORA_SALIDA DATE,
);